# GitHub Funding Configuration
# Muestra el botón "Sponsor" con el icono de corazón en la cabecera de tu repositorio de GitHub

# github: [efrakingz] # Descomenta si activas GitHub Sponsors en https://github.com/sponsors
# ko_fi: efrakingz
# buy_me_a_coffee: efrakingz
custom: ['https://www.paypal.com/donate/?business=efrakingz131@gmail.com&currency_code=USD']
